baseurl = "/"
languageCode = "en-us"
title = "Aselogística"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "ASELOGÍSTICA"

		[params.navigation.links]
			about     = "Nosotros"
			services  = "Servicios"
			portfolio = "Portafolio"
			contact   = "Contacto"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "ASELOGÍSTICA"
		subtitle   = "Servicio de carga internacional desde y hacia Costa Rica"
		buttonText = "Conózcanos"


	# About section
	[params.about]
		headline    = "NUESTRA EMPRESA"
		description = "[Somos una empresa dedicada al transporte aéreo de carga desde y hacia Costa Rica.](//google.com) Nuestro objetivo es escuchar a nuestros  clientes, entender sus necesidades, y trabajar día a día con base en ellas y de esta forma facilitar su logística y el éxito de sus operaciones"
		buttonText  = "Comencemos"


	# Service section
	[params.services]
		headline = "NUESTROS SERVICIOS"

        [[params.services.list]]
            icon = "fa-plane"
            title = "Exportación"
            description = "General: desde etiquetas hasta efectos personales, repuestos o material promocional. Perecederos: flores, frutas, plantas ornamentales. Mercancías peligrosas."

        [[params.services.list]]
			icon = "fa-check-circle"
			title = "Permisos"
			description = "Notas técnicas, transporte normal y caucionado, embalajes"

		[[params.services.list]]
            icon = "fa-flag"
            title = "Importación"
            description = "Permisos y notas técnicas, clareos, nacionalización, transporte interno"
			
		[[params.services.list]]
            icon = "fa-plane"
            title = "Transporte de mascotas"
            description = "Transporte internacional de mascotas desde y hacia Costa Rica"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Contáctenos"
		description = "Póngase en contacto con nosotros con gusto lo atenderemos"
		phone = "506 8859-8455"
		email = "servicioalcliente@aselogistica.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
